### ISSUE TITLE
Master To-Do

### ISSUE THREAD

**Issue by arianabuilds** [siv-org/siv-docs#11]
### Integrate // migrate code from previous design
- [ ] [Protocol Page](https://siv.org/protocol)
    - [ ] End of page 
         - [ ] button/link to go to SIV Docs

## User Experience

- [x] Compare Table Dark Mode: hover effect & numbers to be darker
- [x] The search bar is not accurate // e.g.: I type air gap and it does not give me any results
- [x] Favicon
- [x] Adjust section header font sizes

## Would Be Nice, Not a Barrier

- [x] Benefits -> as in the mobile interface
- [ ] [Verification Methods Overview Table](https://github.com/dsernst/siv-book/issues/12)
- [x] [/vote-selling](https://book.siv.org/further-areas/vote-sellers-dilemma#applicability-to-vote-selling): Improve phone mockup of warning (bit smaller, real phone image, remove heavy black corners, url)
